name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    paths:
      - "Cargo.*"
      - "**/*.rs"
      - ".github/workflows/*.yml"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Build
        run: cargo build --verbose
      - name: Lint
        run: cargo clippy
