name: run

on:
  push:
    branches: [ "main" ]
  pull_request:
    paths:
      - "Cargo.*"
      - "**/*.rs"
      - ".github/workflows/*.yml"

env:
  CARGO_TERM_COLOR: always

jobs:
  run:
    name: run
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --release
      - name: Run
        run: |
          ./target/release/tomo start
          ./target/release/tomo
          ./target/release/tomo break
          ./target/release/tomo stop
